.PHONY: clean All

All:
	@echo "----------Building project:[ SqRootUsingBinSearch - Debug ]----------"
	@cd "SqRootUsingBinSearch" && $(MAKE) -f  "SqRootUsingBinSearch.mk"
clean:
	@echo "----------Cleaning project:[ SqRootUsingBinSearch - Debug ]----------"
	@cd "SqRootUsingBinSearch" && $(MAKE) -f  "SqRootUsingBinSearch.mk" clean
